// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_blocks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentBlocksByUser = `-- name: CountAgentBlocksByUser :one
SELECT count(*) FROM agent_blocks WHERE user_id = $1 OR is_public = true
`

func (q *Queries) CountAgentBlocksByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentBlocksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentBlock = `-- name: CreateAgentBlock :one
INSERT INTO agent_blocks (user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at
`

type CreateAgentBlockParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	Instruction  string      `json:"instruction"`
	SystemPrompt pgtype.Text `json:"system_prompt"`
	AllowedTools []byte      `json:"allowed_tools"`
	OutputSchema []byte      `json:"output_schema"`
	IsPublic     bool        `json:"is_public"`
}

func (q *Queries) CreateAgentBlock(ctx context.Context, arg CreateAgentBlockParams) (AgentBlock, error) {
	row := q.db.QueryRow(ctx, createAgentBlock,
		arg.UserID,
		arg.Name,
		arg.Instruction,
		arg.SystemPrompt,
		arg.AllowedTools,
		arg.OutputSchema,
		arg.IsPublic,
	)
	var i AgentBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Instruction,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.OutputSchema,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgentBlock = `-- name: DeleteAgentBlock :exec
DELETE FROM agent_blocks WHERE id = $1 AND user_id = $2
`

type DeleteAgentBlockParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAgentBlock(ctx context.Context, arg DeleteAgentBlockParams) error {
	_, err := q.db.Exec(ctx, deleteAgentBlock, arg.ID, arg.UserID)
	return err
}

const getAgentBlock = `-- name: GetAgentBlock :one
SELECT id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at FROM agent_blocks WHERE id = $1
`

func (q *Queries) GetAgentBlock(ctx context.Context, id pgtype.UUID) (AgentBlock, error) {
	row := q.db.QueryRow(ctx, getAgentBlock, id)
	var i AgentBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Instruction,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.OutputSchema,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentBlocksByUser = `-- name: ListAgentBlocksByUser :many
SELECT id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at FROM agent_blocks WHERE user_id = $1 OR is_public = true ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAgentBlocksByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAgentBlocksByUser(ctx context.Context, arg ListAgentBlocksByUserParams) ([]AgentBlock, error) {
	rows, err := q.db.Query(ctx, listAgentBlocksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentBlock{}
	for rows.Next() {
		var i AgentBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Instruction,
			&i.SystemPrompt,
			&i.AllowedTools,
			&i.OutputSchema,
			&i.IsPublic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentBlock = `-- name: UpdateAgentBlock :one
UPDATE agent_blocks SET name = $2, instruction = $3, system_prompt = $4, allowed_tools = $5, output_schema = $6, is_public = $7
WHERE id = $1 RETURNING id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at
`

type UpdateAgentBlockParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Instruction  string      `json:"instruction"`
	SystemPrompt pgtype.Text `json:"system_prompt"`
	AllowedTools []byte      `json:"allowed_tools"`
	OutputSchema []byte      `json:"output_schema"`
	IsPublic     bool        `json:"is_public"`
}

func (q *Queries) UpdateAgentBlock(ctx context.Context, arg UpdateAgentBlockParams) (AgentBlock, error) {
	row := q.db.QueryRow(ctx, updateAgentBlock,
		arg.ID,
		arg.Name,
		arg.Instruction,
		arg.SystemPrompt,
		arg.AllowedTools,
		arg.OutputSchema,
		arg.IsPublic,
	)
	var i AgentBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Instruction,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.OutputSchema,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}
