// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO agent_blocks (
  user_id, stage_id, name, objective, input_desc, tools, output_format,
  constraints, examples, instruction, system_prompt, allowed_tools,
  output_schema, is_public, is_template, template_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at, objective, input_desc, tools, output_format, constraints, examples, stage_id, is_template, template_id, updated_at
`

type CreateBlockParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	StageID      pgtype.UUID `json:"stage_id"`
	Name         string      `json:"name"`
	Objective    string      `json:"objective"`
	InputDesc    string      `json:"input_desc"`
	Tools        []string    `json:"tools"`
	OutputFormat string      `json:"output_format"`
	Constraints  pgtype.Text `json:"constraints"`
	Examples     pgtype.Text `json:"examples"`
	Instruction  string      `json:"instruction"`
	SystemPrompt pgtype.Text `json:"system_prompt"`
	AllowedTools []byte      `json:"allowed_tools"`
	OutputSchema []byte      `json:"output_schema"`
	IsPublic     bool        `json:"is_public"`
	IsTemplate   bool        `json:"is_template"`
	TemplateID   pgtype.UUID `json:"template_id"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (AgentBlock, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.UserID,
		arg.StageID,
		arg.Name,
		arg.Objective,
		arg.InputDesc,
		arg.Tools,
		arg.OutputFormat,
		arg.Constraints,
		arg.Examples,
		arg.Instruction,
		arg.SystemPrompt,
		arg.AllowedTools,
		arg.OutputSchema,
		arg.IsPublic,
		arg.IsTemplate,
		arg.TemplateID,
	)
	var i AgentBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Instruction,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.OutputSchema,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Objective,
		&i.InputDesc,
		&i.Tools,
		&i.OutputFormat,
		&i.Constraints,
		&i.Examples,
		&i.StageID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.UpdatedAt,
	)
	return i, err
}

const createMonitorBlock = `-- name: CreateMonitorBlock :one
INSERT INTO monitor_blocks (pipeline_id, block_id, cron, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, pipeline_id, block_id, cron, enabled, created_at, updated_at
`

type CreateMonitorBlockParams struct {
	PipelineID pgtype.UUID `json:"pipeline_id"`
	BlockID    pgtype.UUID `json:"block_id"`
	Cron       string      `json:"cron"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) CreateMonitorBlock(ctx context.Context, arg CreateMonitorBlockParams) (MonitorBlock, error) {
	row := q.db.QueryRow(ctx, createMonitorBlock,
		arg.PipelineID,
		arg.BlockID,
		arg.Cron,
		arg.Enabled,
	)
	var i MonitorBlock
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.BlockID,
		&i.Cron,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM agent_blocks WHERE id = $1 AND user_id = $2
`

type DeleteBlockParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.ID, arg.UserID)
	return err
}

const deleteMonitorBlock = `-- name: DeleteMonitorBlock :exec
DELETE FROM monitor_blocks WHERE id = $1
`

func (q *Queries) DeleteMonitorBlock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitorBlock, id)
	return err
}

const getBlockByID = `-- name: GetBlockByID :one
SELECT id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at, objective, input_desc, tools, output_format, constraints, examples, stage_id, is_template, template_id, updated_at FROM agent_blocks WHERE id = $1
`

func (q *Queries) GetBlockByID(ctx context.Context, id pgtype.UUID) (AgentBlock, error) {
	row := q.db.QueryRow(ctx, getBlockByID, id)
	var i AgentBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Instruction,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.OutputSchema,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Objective,
		&i.InputDesc,
		&i.Tools,
		&i.OutputFormat,
		&i.Constraints,
		&i.Examples,
		&i.StageID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlocksByStage = `-- name: ListBlocksByStage :many
SELECT id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at, objective, input_desc, tools, output_format, constraints, examples, stage_id, is_template, template_id, updated_at FROM agent_blocks WHERE stage_id = $1 ORDER BY created_at
`

func (q *Queries) ListBlocksByStage(ctx context.Context, stageID pgtype.UUID) ([]AgentBlock, error) {
	rows, err := q.db.Query(ctx, listBlocksByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentBlock{}
	for rows.Next() {
		var i AgentBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Instruction,
			&i.SystemPrompt,
			&i.AllowedTools,
			&i.OutputSchema,
			&i.IsPublic,
			&i.CreatedAt,
			&i.Objective,
			&i.InputDesc,
			&i.Tools,
			&i.OutputFormat,
			&i.Constraints,
			&i.Examples,
			&i.StageID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByUser = `-- name: ListBlocksByUser :many
SELECT id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at, objective, input_desc, tools, output_format, constraints, examples, stage_id, is_template, template_id, updated_at FROM agent_blocks
WHERE user_id = $1 AND stage_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListBlocksByUser(ctx context.Context, userID pgtype.UUID) ([]AgentBlock, error) {
	rows, err := q.db.Query(ctx, listBlocksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentBlock{}
	for rows.Next() {
		var i AgentBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Instruction,
			&i.SystemPrompt,
			&i.AllowedTools,
			&i.OutputSchema,
			&i.IsPublic,
			&i.CreatedAt,
			&i.Objective,
			&i.InputDesc,
			&i.Tools,
			&i.OutputFormat,
			&i.Constraints,
			&i.Examples,
			&i.StageID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByPipeline = `-- name: ListMonitorsByPipeline :many
SELECT id, pipeline_id, block_id, cron, enabled, created_at, updated_at FROM monitor_blocks WHERE pipeline_id = $1
`

func (q *Queries) ListMonitorsByPipeline(ctx context.Context, pipelineID pgtype.UUID) ([]MonitorBlock, error) {
	rows, err := q.db.Query(ctx, listMonitorsByPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorBlock{}
	for rows.Next() {
		var i MonitorBlock
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.BlockID,
			&i.Cron,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at, objective, input_desc, tools, output_format, constraints, examples, stage_id, is_template, template_id, updated_at FROM agent_blocks
WHERE (user_id = $1 OR is_public = true) AND is_template = true
ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context, userID pgtype.UUID) ([]AgentBlock, error) {
	rows, err := q.db.Query(ctx, listTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentBlock{}
	for rows.Next() {
		var i AgentBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Instruction,
			&i.SystemPrompt,
			&i.AllowedTools,
			&i.OutputSchema,
			&i.IsPublic,
			&i.CreatedAt,
			&i.Objective,
			&i.InputDesc,
			&i.Tools,
			&i.OutputFormat,
			&i.Constraints,
			&i.Examples,
			&i.StageID,
			&i.IsTemplate,
			&i.TemplateID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlock = `-- name: UpdateBlock :one
UPDATE agent_blocks
SET name = $2, objective = $3, input_desc = $4, tools = $5, output_format = $6,
    constraints = $7, examples = $8, instruction = $9, system_prompt = $10,
    allowed_tools = $11, output_schema = $12, is_public = $13, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, instruction, system_prompt, allowed_tools, output_schema, is_public, created_at, objective, input_desc, tools, output_format, constraints, examples, stage_id, is_template, template_id, updated_at
`

type UpdateBlockParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Objective    string      `json:"objective"`
	InputDesc    string      `json:"input_desc"`
	Tools        []string    `json:"tools"`
	OutputFormat string      `json:"output_format"`
	Constraints  pgtype.Text `json:"constraints"`
	Examples     pgtype.Text `json:"examples"`
	Instruction  string      `json:"instruction"`
	SystemPrompt pgtype.Text `json:"system_prompt"`
	AllowedTools []byte      `json:"allowed_tools"`
	OutputSchema []byte      `json:"output_schema"`
	IsPublic     bool        `json:"is_public"`
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) (AgentBlock, error) {
	row := q.db.QueryRow(ctx, updateBlock,
		arg.ID,
		arg.Name,
		arg.Objective,
		arg.InputDesc,
		arg.Tools,
		arg.OutputFormat,
		arg.Constraints,
		arg.Examples,
		arg.Instruction,
		arg.SystemPrompt,
		arg.AllowedTools,
		arg.OutputSchema,
		arg.IsPublic,
	)
	var i AgentBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Instruction,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.OutputSchema,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Objective,
		&i.InputDesc,
		&i.Tools,
		&i.OutputFormat,
		&i.Constraints,
		&i.Examples,
		&i.StageID,
		&i.IsTemplate,
		&i.TemplateID,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitorBlock = `-- name: UpdateMonitorBlock :one
UPDATE monitor_blocks SET cron = $2, enabled = $3, updated_at = now() WHERE id = $1
RETURNING id, pipeline_id, block_id, cron, enabled, created_at, updated_at
`

type UpdateMonitorBlockParams struct {
	ID      pgtype.UUID `json:"id"`
	Cron    string      `json:"cron"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpdateMonitorBlock(ctx context.Context, arg UpdateMonitorBlockParams) (MonitorBlock, error) {
	row := q.db.QueryRow(ctx, updateMonitorBlock, arg.ID, arg.Cron, arg.Enabled)
	var i MonitorBlock
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.BlockID,
		&i.Cron,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
