// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCasesByUser = `-- name: CountCasesByUser :one
SELECT count(*) FROM cases WHERE user_id = $1
`

func (q *Queries) CountCasesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCasesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCasesByUserAndStatus = `-- name: CountCasesByUserAndStatus :one
SELECT count(*) FROM cases WHERE user_id = $1 AND status = $2
`

type CountCasesByUserAndStatusParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status CaseStatus  `json:"status"`
}

func (q *Queries) CountCasesByUserAndStatus(ctx context.Context, arg CountCasesByUserAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCasesByUserAndStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCase = `-- name: CreateCase :one
INSERT INTO cases (user_id, pipeline_id, symbol, event_date, event_snapshot, success_script, failure_script)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, pipeline_id, symbol, status, event_date, event_snapshot, success_script, failure_script, closed_at, closed_reason, created_at, updated_at, dsl_polling_enabled
`

type CreateCaseParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PipelineID    pgtype.UUID `json:"pipeline_id"`
	Symbol        string      `json:"symbol"`
	EventDate     pgtype.Date `json:"event_date"`
	EventSnapshot []byte      `json:"event_snapshot"`
	SuccessScript string      `json:"success_script"`
	FailureScript string      `json:"failure_script"`
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error) {
	row := q.db.QueryRow(ctx, createCase,
		arg.UserID,
		arg.PipelineID,
		arg.Symbol,
		arg.EventDate,
		arg.EventSnapshot,
		arg.SuccessScript,
		arg.FailureScript,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PipelineID,
		&i.Symbol,
		&i.Status,
		&i.EventDate,
		&i.EventSnapshot,
		&i.SuccessScript,
		&i.FailureScript,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DslPollingEnabled,
	)
	return i, err
}

const deleteCase = `-- name: DeleteCase :exec
DELETE FROM cases WHERE id = $1 AND user_id = $2
`

type DeleteCaseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCase(ctx context.Context, arg DeleteCaseParams) error {
	_, err := q.db.Exec(ctx, deleteCase, arg.ID, arg.UserID)
	return err
}

const getCase = `-- name: GetCase :one
SELECT id, user_id, pipeline_id, symbol, status, event_date, event_snapshot, success_script, failure_script, closed_at, closed_reason, created_at, updated_at, dsl_polling_enabled FROM cases WHERE id = $1 AND user_id = $2
`

type GetCaseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCase(ctx context.Context, arg GetCaseParams) (Case, error) {
	row := q.db.QueryRow(ctx, getCase, arg.ID, arg.UserID)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PipelineID,
		&i.Symbol,
		&i.Status,
		&i.EventDate,
		&i.EventSnapshot,
		&i.SuccessScript,
		&i.FailureScript,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DslPollingEnabled,
	)
	return i, err
}

const listCasesByUser = `-- name: ListCasesByUser :many
SELECT id, user_id, pipeline_id, symbol, status, event_date, event_snapshot, success_script, failure_script, closed_at, closed_reason, created_at, updated_at, dsl_polling_enabled FROM cases WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCasesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCasesByUser(ctx context.Context, arg ListCasesByUserParams) ([]Case, error) {
	rows, err := q.db.Query(ctx, listCasesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Case{}
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PipelineID,
			&i.Symbol,
			&i.Status,
			&i.EventDate,
			&i.EventSnapshot,
			&i.SuccessScript,
			&i.FailureScript,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DslPollingEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasesByUserAndStatus = `-- name: ListCasesByUserAndStatus :many
SELECT id, user_id, pipeline_id, symbol, status, event_date, event_snapshot, success_script, failure_script, closed_at, closed_reason, created_at, updated_at, dsl_polling_enabled FROM cases WHERE user_id = $1 AND status = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListCasesByUserAndStatusParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status CaseStatus  `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCasesByUserAndStatus(ctx context.Context, arg ListCasesByUserAndStatusParams) ([]Case, error) {
	rows, err := q.db.Query(ctx, listCasesByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Case{}
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PipelineID,
			&i.Symbol,
			&i.Status,
			&i.EventDate,
			&i.EventSnapshot,
			&i.SuccessScript,
			&i.FailureScript,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DslPollingEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaseStatus = `-- name: UpdateCaseStatus :one
UPDATE cases SET status = $2, closed_at = $3, closed_reason = $4 WHERE id = $1 RETURNING id, user_id, pipeline_id, symbol, status, event_date, event_snapshot, success_script, failure_script, closed_at, closed_reason, created_at, updated_at, dsl_polling_enabled
`

type UpdateCaseStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       CaseStatus  `json:"status"`
	ClosedAt     pgtype.Date `json:"closed_at"`
	ClosedReason pgtype.Text `json:"closed_reason"`
}

func (q *Queries) UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) (Case, error) {
	row := q.db.QueryRow(ctx, updateCaseStatus,
		arg.ID,
		arg.Status,
		arg.ClosedAt,
		arg.ClosedReason,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PipelineID,
		&i.Symbol,
		&i.Status,
		&i.EventDate,
		&i.EventSnapshot,
		&i.SuccessScript,
		&i.FailureScript,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DslPollingEnabled,
	)
	return i, err
}
