// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: marketplace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearVerification = `-- name: ClearVerification :exec
UPDATE marketplace_items
SET verified = false,
    backtest_job_id = NULL,
    backtest_win_rate = NULL,
    backtest_avg_return = NULL,
    backtest_total_events = NULL
WHERE id = $1
`

func (q *Queries) ClearVerification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearVerification, id)
	return err
}

const countMarketplaceItems = `-- name: CountMarketplaceItems :one
SELECT COUNT(*) FROM marketplace_items
WHERE status = 'ACTIVE'
  AND ($1::marketplace_item_type IS NULL OR type = $1)
  AND ($2::boolean IS NULL OR verified = $2)
  AND ($3::text[] IS NULL OR tags && $3)
`

type CountMarketplaceItemsParams struct {
	Column1 MarketplaceItemType `json:"column_1"`
	Column2 bool                `json:"column_2"`
	Column3 []string            `json:"column_3"`
}

func (q *Queries) CountMarketplaceItems(ctx context.Context, arg CountMarketplaceItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMarketplaceItems, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMyMarketplaceItems = `-- name: CountMyMarketplaceItems :one
SELECT COUNT(*) FROM marketplace_items
WHERE user_id = $1 AND status != 'REMOVED'
`

func (q *Queries) CountMyMarketplaceItems(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMyMarketplaceItems, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchMarketplaceItems = `-- name: CountSearchMarketplaceItems :one
SELECT COUNT(*) FROM marketplace_items
WHERE search_vector @@ plainto_tsquery('simple', $1)
  AND status = 'ACTIVE'
  AND ($2::marketplace_item_type IS NULL OR type = $2)
  AND ($3::boolean IS NULL OR verified = $3)
  AND ($4::text[] IS NULL OR tags && $4)
`

type CountSearchMarketplaceItemsParams struct {
	PlaintoTsquery string              `json:"plainto_tsquery"`
	Column2        MarketplaceItemType `json:"column_2"`
	Column3        bool                `json:"column_3"`
	Column4        []string            `json:"column_4"`
}

func (q *Queries) CountSearchMarketplaceItems(ctx context.Context, arg CountSearchMarketplaceItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchMarketplaceItems,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLike = `-- name: CreateLike :one

INSERT INTO marketplace_likes (user_id, item_id)
VALUES ($1, $2)
ON CONFLICT (user_id, item_id) DO NOTHING
RETURNING id, user_id, item_id, created_at
`

type CreateLikeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ItemID pgtype.UUID `json:"item_id"`
}

// =============================================================================
// Likes
// =============================================================================
func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (MarketplaceLike, error) {
	row := q.db.QueryRow(ctx, createLike, arg.UserID, arg.ItemID)
	var i MarketplaceLike
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.CreatedAt,
	)
	return i, err
}

const createMarketplaceItem = `-- name: CreateMarketplaceItem :one

INSERT INTO marketplace_items (
  user_id, type, title, description, tags,
  pipeline_id, agent_block_id, search_preset_id, judgment_script_id,
  forked_from_id
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10
) RETURNING id, user_id, type, title, description, tags, pipeline_id, agent_block_id, search_preset_id, judgment_script_id, forked_from_id, fork_count, usage_count, view_count, like_count, verified, backtest_job_id, backtest_win_rate, backtest_avg_return, backtest_total_events, status, published_at, updated_at, search_vector
`

type CreateMarketplaceItemParams struct {
	UserID           pgtype.UUID         `json:"user_id"`
	Type             MarketplaceItemType `json:"type"`
	Title            string              `json:"title"`
	Description      string              `json:"description"`
	Tags             []string            `json:"tags"`
	PipelineID       pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID     pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID   pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID     pgtype.UUID         `json:"forked_from_id"`
}

// =============================================================================
// Marketplace Item CRUD
// =============================================================================
func (q *Queries) CreateMarketplaceItem(ctx context.Context, arg CreateMarketplaceItemParams) (MarketplaceItem, error) {
	row := q.db.QueryRow(ctx, createMarketplaceItem,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.PipelineID,
		arg.AgentBlockID,
		arg.SearchPresetID,
		arg.JudgmentScriptID,
		arg.ForkedFromID,
	)
	var i MarketplaceItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.PipelineID,
		&i.AgentBlockID,
		&i.SearchPresetID,
		&i.JudgmentScriptID,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.UsageCount,
		&i.ViewCount,
		&i.LikeCount,
		&i.Verified,
		&i.BacktestJobID,
		&i.BacktestWinRate,
		&i.BacktestAvgReturn,
		&i.BacktestTotalEvents,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const createUsageLog = `-- name: CreateUsageLog :one

INSERT INTO marketplace_usage_logs (user_id, item_id, action)
VALUES ($1, $2, $3)
RETURNING id, user_id, item_id, action, created_at
`

type CreateUsageLogParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ItemID pgtype.UUID `json:"item_id"`
	Action UsageAction `json:"action"`
}

// =============================================================================
// Usage Logs
// =============================================================================
func (q *Queries) CreateUsageLog(ctx context.Context, arg CreateUsageLogParams) (MarketplaceUsageLog, error) {
	row := q.db.QueryRow(ctx, createUsageLog, arg.UserID, arg.ItemID, arg.Action)
	var i MarketplaceUsageLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const decrementLikeCount = `-- name: DecrementLikeCount :exec
UPDATE marketplace_items
SET like_count = GREATEST(like_count - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementLikeCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementLikeCount, id)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM marketplace_likes
WHERE user_id = $1 AND item_id = $2
`

type DeleteLikeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ItemID pgtype.UUID `json:"item_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.UserID, arg.ItemID)
	return err
}

const deleteMarketplaceItem = `-- name: DeleteMarketplaceItem :exec
UPDATE marketplace_items
SET status = 'REMOVED'
WHERE id = $1 AND user_id = $2
`

type DeleteMarketplaceItemParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMarketplaceItem(ctx context.Context, arg DeleteMarketplaceItemParams) error {
	_, err := q.db.Exec(ctx, deleteMarketplaceItem, arg.ID, arg.UserID)
	return err
}

const findItemByAgentBlockID = `-- name: FindItemByAgentBlockID :one
SELECT id FROM marketplace_items
WHERE agent_block_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) FindItemByAgentBlockID(ctx context.Context, agentBlockID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findItemByAgentBlockID, agentBlockID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findItemByJudgmentScriptID = `-- name: FindItemByJudgmentScriptID :one
SELECT id FROM marketplace_items
WHERE judgment_script_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) FindItemByJudgmentScriptID(ctx context.Context, judgmentScriptID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findItemByJudgmentScriptID, judgmentScriptID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findItemByPipelineID = `-- name: FindItemByPipelineID :one
SELECT id FROM marketplace_items
WHERE pipeline_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) FindItemByPipelineID(ctx context.Context, pipelineID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findItemByPipelineID, pipelineID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findItemBySearchPresetID = `-- name: FindItemBySearchPresetID :one
SELECT id FROM marketplace_items
WHERE search_preset_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) FindItemBySearchPresetID(ctx context.Context, searchPresetID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findItemBySearchPresetID, searchPresetID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLikeByUserAndItem = `-- name: GetLikeByUserAndItem :one
SELECT id, user_id, item_id, created_at FROM marketplace_likes
WHERE user_id = $1 AND item_id = $2
`

type GetLikeByUserAndItemParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ItemID pgtype.UUID `json:"item_id"`
}

func (q *Queries) GetLikeByUserAndItem(ctx context.Context, arg GetLikeByUserAndItemParams) (MarketplaceLike, error) {
	row := q.db.QueryRow(ctx, getLikeByUserAndItem, arg.UserID, arg.ItemID)
	var i MarketplaceLike
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.CreatedAt,
	)
	return i, err
}

const getMarketplaceItemByID = `-- name: GetMarketplaceItemByID :one
SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.id = $1
`

type GetMarketplaceItemByIDRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
}

func (q *Queries) GetMarketplaceItemByID(ctx context.Context, id pgtype.UUID) (GetMarketplaceItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getMarketplaceItemByID, id)
	var i GetMarketplaceItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.PipelineID,
		&i.AgentBlockID,
		&i.SearchPresetID,
		&i.JudgmentScriptID,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.UsageCount,
		&i.ViewCount,
		&i.LikeCount,
		&i.Verified,
		&i.BacktestJobID,
		&i.BacktestWinRate,
		&i.BacktestAvgReturn,
		&i.BacktestTotalEvents,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorImage,
	)
	return i, err
}

const getMarketplaceItemWithForkOrigin = `-- name: GetMarketplaceItemWithForkOrigin :one
SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image,
       fo.id AS fork_origin_id, fo.title AS fork_origin_title,
       fu.name AS fork_origin_author_name
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
LEFT JOIN marketplace_items fo ON mi.forked_from_id = fo.id
LEFT JOIN users fu ON fo.user_id = fu.id
WHERE mi.id = $1
`

type GetMarketplaceItemWithForkOriginRow struct {
	ID                   pgtype.UUID         `json:"id"`
	UserID               pgtype.UUID         `json:"user_id"`
	Type                 MarketplaceItemType `json:"type"`
	Title                string              `json:"title"`
	Description          string              `json:"description"`
	Tags                 []string            `json:"tags"`
	PipelineID           pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID         pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID       pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID     pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID         pgtype.UUID         `json:"forked_from_id"`
	ForkCount            int32               `json:"fork_count"`
	UsageCount           int32               `json:"usage_count"`
	ViewCount            int32               `json:"view_count"`
	LikeCount            int32               `json:"like_count"`
	Verified             bool                `json:"verified"`
	BacktestJobID        pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate      pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn    pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents  pgtype.Int4         `json:"backtest_total_events"`
	Status               MarketplaceStatus   `json:"status"`
	PublishedAt          pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt            pgtype.Timestamptz  `json:"updated_at"`
	SearchVector         interface{}         `json:"search_vector"`
	AuthorID             pgtype.UUID         `json:"author_id"`
	AuthorName           pgtype.Text         `json:"author_name"`
	AuthorImage          pgtype.Text         `json:"author_image"`
	ForkOriginID         pgtype.UUID         `json:"fork_origin_id"`
	ForkOriginTitle      pgtype.Text         `json:"fork_origin_title"`
	ForkOriginAuthorName pgtype.Text         `json:"fork_origin_author_name"`
}

func (q *Queries) GetMarketplaceItemWithForkOrigin(ctx context.Context, id pgtype.UUID) (GetMarketplaceItemWithForkOriginRow, error) {
	row := q.db.QueryRow(ctx, getMarketplaceItemWithForkOrigin, id)
	var i GetMarketplaceItemWithForkOriginRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.PipelineID,
		&i.AgentBlockID,
		&i.SearchPresetID,
		&i.JudgmentScriptID,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.UsageCount,
		&i.ViewCount,
		&i.LikeCount,
		&i.Verified,
		&i.BacktestJobID,
		&i.BacktestWinRate,
		&i.BacktestAvgReturn,
		&i.BacktestTotalEvents,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorImage,
		&i.ForkOriginID,
		&i.ForkOriginTitle,
		&i.ForkOriginAuthorName,
	)
	return i, err
}

const getRecentViewLog = `-- name: GetRecentViewLog :one
SELECT id, user_id, item_id, action, created_at FROM marketplace_usage_logs
WHERE item_id = $1 AND user_id = $2 AND action = 'VIEW'
  AND created_at >= $3
ORDER BY created_at DESC
LIMIT 1
`

type GetRecentViewLogParams struct {
	ItemID    pgtype.UUID        `json:"item_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentViewLog(ctx context.Context, arg GetRecentViewLogParams) (MarketplaceUsageLog, error) {
	row := q.db.QueryRow(ctx, getRecentViewLog, arg.ItemID, arg.UserID, arg.CreatedAt)
	var i MarketplaceUsageLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const incrementForkCount = `-- name: IncrementForkCount :exec
UPDATE marketplace_items
SET fork_count = fork_count + 1
WHERE id = $1
`

func (q *Queries) IncrementForkCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementForkCount, id)
	return err
}

const incrementLikeCount = `-- name: IncrementLikeCount :exec
UPDATE marketplace_items
SET like_count = like_count + 1
WHERE id = $1
`

func (q *Queries) IncrementLikeCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLikeCount, id)
	return err
}

const incrementUsageCount = `-- name: IncrementUsageCount :exec
UPDATE marketplace_items
SET usage_count = usage_count + 1
WHERE id = $1
`

func (q *Queries) IncrementUsageCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementUsageCount, id)
	return err
}

const incrementViewCount = `-- name: IncrementViewCount :exec

UPDATE marketplace_items
SET view_count = view_count + 1
WHERE id = $1
`

// =============================================================================
// Statistics Updates
// =============================================================================
func (q *Queries) IncrementViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const isItemLikedByUser = `-- name: IsItemLikedByUser :one
SELECT EXISTS(
  SELECT 1 FROM marketplace_likes WHERE user_id = $1 AND item_id = $2
) AS liked
`

type IsItemLikedByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ItemID pgtype.UUID `json:"item_id"`
}

func (q *Queries) IsItemLikedByUser(ctx context.Context, arg IsItemLikedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isItemLikedByUser, arg.UserID, arg.ItemID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const listActiveItemIDs = `-- name: ListActiveItemIDs :many
SELECT id FROM marketplace_items WHERE status = 'ACTIVE'
`

func (q *Queries) ListActiveItemIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveItemIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceItemsByMostForked = `-- name: ListMarketplaceItemsByMostForked :many
SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.status = 'ACTIVE'
  AND ($1::marketplace_item_type IS NULL OR mi.type = $1)
  AND ($2::boolean IS NULL OR mi.verified = $2)
  AND ($3::text[] IS NULL OR mi.tags && $3)
ORDER BY mi.fork_count DESC
LIMIT $4 OFFSET $5
`

type ListMarketplaceItemsByMostForkedParams struct {
	Column1 MarketplaceItemType `json:"column_1"`
	Column2 bool                `json:"column_2"`
	Column3 []string            `json:"column_3"`
	Limit   int32               `json:"limit"`
	Offset  int32               `json:"offset"`
}

type ListMarketplaceItemsByMostForkedRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
}

func (q *Queries) ListMarketplaceItemsByMostForked(ctx context.Context, arg ListMarketplaceItemsByMostForkedParams) ([]ListMarketplaceItemsByMostForkedRow, error) {
	rows, err := q.db.Query(ctx, listMarketplaceItemsByMostForked,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketplaceItemsByMostForkedRow{}
	for rows.Next() {
		var i ListMarketplaceItemsByMostForkedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.PipelineID,
			&i.AgentBlockID,
			&i.SearchPresetID,
			&i.JudgmentScriptID,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.UsageCount,
			&i.ViewCount,
			&i.LikeCount,
			&i.Verified,
			&i.BacktestJobID,
			&i.BacktestWinRate,
			&i.BacktestAvgReturn,
			&i.BacktestTotalEvents,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceItemsByPerformance = `-- name: ListMarketplaceItemsByPerformance :many
SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.status = 'ACTIVE'
  AND ($1::marketplace_item_type IS NULL OR mi.type = $1)
  AND ($2::boolean IS NULL OR mi.verified = $2)
  AND ($3::text[] IS NULL OR mi.tags && $3)
ORDER BY mi.backtest_win_rate DESC NULLS LAST
LIMIT $4 OFFSET $5
`

type ListMarketplaceItemsByPerformanceParams struct {
	Column1 MarketplaceItemType `json:"column_1"`
	Column2 bool                `json:"column_2"`
	Column3 []string            `json:"column_3"`
	Limit   int32               `json:"limit"`
	Offset  int32               `json:"offset"`
}

type ListMarketplaceItemsByPerformanceRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
}

func (q *Queries) ListMarketplaceItemsByPerformance(ctx context.Context, arg ListMarketplaceItemsByPerformanceParams) ([]ListMarketplaceItemsByPerformanceRow, error) {
	rows, err := q.db.Query(ctx, listMarketplaceItemsByPerformance,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketplaceItemsByPerformanceRow{}
	for rows.Next() {
		var i ListMarketplaceItemsByPerformanceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.PipelineID,
			&i.AgentBlockID,
			&i.SearchPresetID,
			&i.JudgmentScriptID,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.UsageCount,
			&i.ViewCount,
			&i.LikeCount,
			&i.Verified,
			&i.BacktestJobID,
			&i.BacktestWinRate,
			&i.BacktestAvgReturn,
			&i.BacktestTotalEvents,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceItemsByPopular = `-- name: ListMarketplaceItemsByPopular :many
SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.status = 'ACTIVE'
  AND ($1::marketplace_item_type IS NULL OR mi.type = $1)
  AND ($2::boolean IS NULL OR mi.verified = $2)
  AND ($3::text[] IS NULL OR mi.tags && $3)
ORDER BY mi.usage_count DESC
LIMIT $4 OFFSET $5
`

type ListMarketplaceItemsByPopularParams struct {
	Column1 MarketplaceItemType `json:"column_1"`
	Column2 bool                `json:"column_2"`
	Column3 []string            `json:"column_3"`
	Limit   int32               `json:"limit"`
	Offset  int32               `json:"offset"`
}

type ListMarketplaceItemsByPopularRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
}

func (q *Queries) ListMarketplaceItemsByPopular(ctx context.Context, arg ListMarketplaceItemsByPopularParams) ([]ListMarketplaceItemsByPopularRow, error) {
	rows, err := q.db.Query(ctx, listMarketplaceItemsByPopular,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketplaceItemsByPopularRow{}
	for rows.Next() {
		var i ListMarketplaceItemsByPopularRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.PipelineID,
			&i.AgentBlockID,
			&i.SearchPresetID,
			&i.JudgmentScriptID,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.UsageCount,
			&i.ViewCount,
			&i.LikeCount,
			&i.Verified,
			&i.BacktestJobID,
			&i.BacktestWinRate,
			&i.BacktestAvgReturn,
			&i.BacktestTotalEvents,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceItemsByRecent = `-- name: ListMarketplaceItemsByRecent :many

SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.status = 'ACTIVE'
  AND ($1::marketplace_item_type IS NULL OR mi.type = $1)
  AND ($2::boolean IS NULL OR mi.verified = $2)
  AND ($3::text[] IS NULL OR mi.tags && $3)
ORDER BY mi.published_at DESC
LIMIT $4 OFFSET $5
`

type ListMarketplaceItemsByRecentParams struct {
	Column1 MarketplaceItemType `json:"column_1"`
	Column2 bool                `json:"column_2"`
	Column3 []string            `json:"column_3"`
	Limit   int32               `json:"limit"`
	Offset  int32               `json:"offset"`
}

type ListMarketplaceItemsByRecentRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
}

// =============================================================================
// Listing & Filtering (no full-text search)
// =============================================================================
func (q *Queries) ListMarketplaceItemsByRecent(ctx context.Context, arg ListMarketplaceItemsByRecentParams) ([]ListMarketplaceItemsByRecentRow, error) {
	rows, err := q.db.Query(ctx, listMarketplaceItemsByRecent,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketplaceItemsByRecentRow{}
	for rows.Next() {
		var i ListMarketplaceItemsByRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.PipelineID,
			&i.AgentBlockID,
			&i.SearchPresetID,
			&i.JudgmentScriptID,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.UsageCount,
			&i.ViewCount,
			&i.LikeCount,
			&i.Verified,
			&i.BacktestJobID,
			&i.BacktestWinRate,
			&i.BacktestAvgReturn,
			&i.BacktestTotalEvents,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyMarketplaceItems = `-- name: ListMyMarketplaceItems :many

SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.user_id = $1 AND mi.status != 'REMOVED'
ORDER BY mi.published_at DESC
LIMIT $2 OFFSET $3
`

type ListMyMarketplaceItemsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListMyMarketplaceItemsRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
}

// =============================================================================
// User's own items
// =============================================================================
func (q *Queries) ListMyMarketplaceItems(ctx context.Context, arg ListMyMarketplaceItemsParams) ([]ListMyMarketplaceItemsRow, error) {
	rows, err := q.db.Query(ctx, listMyMarketplaceItems, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyMarketplaceItemsRow{}
	for rows.Next() {
		var i ListMyMarketplaceItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.PipelineID,
			&i.AgentBlockID,
			&i.SearchPresetID,
			&i.JudgmentScriptID,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.UsageCount,
			&i.ViewCount,
			&i.LikeCount,
			&i.Verified,
			&i.BacktestJobID,
			&i.BacktestWinRate,
			&i.BacktestAvgReturn,
			&i.BacktestTotalEvents,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshItemForkCount = `-- name: RefreshItemForkCount :exec

UPDATE marketplace_items mi
SET fork_count = (
  SELECT COUNT(*) FROM marketplace_items WHERE forked_from_id = mi.id
)
WHERE mi.id = $1
`

// =============================================================================
// Batch Stats Refresh (for asynq worker)
// =============================================================================
func (q *Queries) RefreshItemForkCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshItemForkCount, id)
	return err
}

const refreshItemLikeCount = `-- name: RefreshItemLikeCount :exec
UPDATE marketplace_items mi
SET like_count = (
  SELECT COUNT(*) FROM marketplace_likes WHERE item_id = mi.id
)
WHERE mi.id = $1
`

func (q *Queries) RefreshItemLikeCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshItemLikeCount, id)
	return err
}

const refreshItemUsageCount = `-- name: RefreshItemUsageCount :exec
UPDATE marketplace_items mi
SET usage_count = (
  SELECT COUNT(*) FROM marketplace_usage_logs WHERE item_id = mi.id AND action = 'EXECUTE'
)
WHERE mi.id = $1
`

func (q *Queries) RefreshItemUsageCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshItemUsageCount, id)
	return err
}

const refreshItemViewCount = `-- name: RefreshItemViewCount :exec
UPDATE marketplace_items mi
SET view_count = (
  SELECT COUNT(*) FROM marketplace_usage_logs WHERE item_id = mi.id AND action = 'VIEW'
)
WHERE mi.id = $1
`

func (q *Queries) RefreshItemViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshItemViewCount, id)
	return err
}

const searchMarketplaceItems = `-- name: SearchMarketplaceItems :many

SELECT mi.id, mi.user_id, mi.type, mi.title, mi.description, mi.tags, mi.pipeline_id, mi.agent_block_id, mi.search_preset_id, mi.judgment_script_id, mi.forked_from_id, mi.fork_count, mi.usage_count, mi.view_count, mi.like_count, mi.verified, mi.backtest_job_id, mi.backtest_win_rate, mi.backtest_avg_return, mi.backtest_total_events, mi.status, mi.published_at, mi.updated_at, mi.search_vector,
       u.id AS author_id, u.name AS author_name, u.image AS author_image,
       ts_rank(mi.search_vector, plainto_tsquery('simple', $1)) AS rank
FROM marketplace_items mi
JOIN users u ON mi.user_id = u.id
WHERE mi.search_vector @@ plainto_tsquery('simple', $1)
  AND mi.status = 'ACTIVE'
  AND ($2::marketplace_item_type IS NULL OR mi.type = $2)
  AND ($3::boolean IS NULL OR mi.verified = $3)
  AND ($4::text[] IS NULL OR mi.tags && $4)
ORDER BY rank DESC
LIMIT $5 OFFSET $6
`

type SearchMarketplaceItemsParams struct {
	PlaintoTsquery string              `json:"plainto_tsquery"`
	Column2        MarketplaceItemType `json:"column_2"`
	Column3        bool                `json:"column_3"`
	Column4        []string            `json:"column_4"`
	Limit          int32               `json:"limit"`
	Offset         int32               `json:"offset"`
}

type SearchMarketplaceItemsRow struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
	AuthorID            pgtype.UUID         `json:"author_id"`
	AuthorName          pgtype.Text         `json:"author_name"`
	AuthorImage         pgtype.Text         `json:"author_image"`
	Rank                float32             `json:"rank"`
}

// =============================================================================
// Full-Text Search (PostgreSQL tsvector)
// =============================================================================
func (q *Queries) SearchMarketplaceItems(ctx context.Context, arg SearchMarketplaceItemsParams) ([]SearchMarketplaceItemsRow, error) {
	rows, err := q.db.Query(ctx, searchMarketplaceItems,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMarketplaceItemsRow{}
	for rows.Next() {
		var i SearchMarketplaceItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.PipelineID,
			&i.AgentBlockID,
			&i.SearchPresetID,
			&i.JudgmentScriptID,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.UsageCount,
			&i.ViewCount,
			&i.LikeCount,
			&i.Verified,
			&i.BacktestJobID,
			&i.BacktestWinRate,
			&i.BacktestAvgReturn,
			&i.BacktestTotalEvents,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorImage,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMarketplaceItemStatus = `-- name: SetMarketplaceItemStatus :exec
UPDATE marketplace_items
SET status = $2
WHERE id = $1 AND user_id = $3
`

type SetMarketplaceItemStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status MarketplaceStatus `json:"status"`
	UserID pgtype.UUID       `json:"user_id"`
}

func (q *Queries) SetMarketplaceItemStatus(ctx context.Context, arg SetMarketplaceItemStatusParams) error {
	_, err := q.db.Exec(ctx, setMarketplaceItemStatus, arg.ID, arg.Status, arg.UserID)
	return err
}

const setVerificationStats = `-- name: SetVerificationStats :exec
UPDATE marketplace_items
SET verified = true,
    backtest_job_id = $2,
    backtest_win_rate = $3,
    backtest_avg_return = $4,
    backtest_total_events = $5
WHERE id = $1
`

type SetVerificationStatsParams struct {
	ID                  pgtype.UUID    `json:"id"`
	BacktestJobID       pgtype.UUID    `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4    `json:"backtest_total_events"`
}

func (q *Queries) SetVerificationStats(ctx context.Context, arg SetVerificationStatsParams) error {
	_, err := q.db.Exec(ctx, setVerificationStats,
		arg.ID,
		arg.BacktestJobID,
		arg.BacktestWinRate,
		arg.BacktestAvgReturn,
		arg.BacktestTotalEvents,
	)
	return err
}

const updateMarketplaceItem = `-- name: UpdateMarketplaceItem :one
UPDATE marketplace_items
SET title = $2,
    description = $3,
    tags = $4
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, type, title, description, tags, pipeline_id, agent_block_id, search_preset_id, judgment_script_id, forked_from_id, fork_count, usage_count, view_count, like_count, verified, backtest_job_id, backtest_win_rate, backtest_avg_return, backtest_total_events, status, published_at, updated_at, search_vector
`

type UpdateMarketplaceItemParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Tags        []string    `json:"tags"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMarketplaceItem(ctx context.Context, arg UpdateMarketplaceItemParams) (MarketplaceItem, error) {
	row := q.db.QueryRow(ctx, updateMarketplaceItem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.UserID,
	)
	var i MarketplaceItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.PipelineID,
		&i.AgentBlockID,
		&i.SearchPresetID,
		&i.JudgmentScriptID,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.UsageCount,
		&i.ViewCount,
		&i.LikeCount,
		&i.Verified,
		&i.BacktestJobID,
		&i.BacktestWinRate,
		&i.BacktestAvgReturn,
		&i.BacktestTotalEvents,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
