// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CaseStatus string

const (
	CaseStatusLIVE          CaseStatus = "LIVE"
	CaseStatusCLOSEDSUCCESS CaseStatus = "CLOSED_SUCCESS"
	CaseStatusCLOSEDFAILURE CaseStatus = "CLOSED_FAILURE"
	CaseStatusBACKTEST      CaseStatus = "BACKTEST"
)

func (e *CaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CaseStatus(s)
	case string:
		*e = CaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CaseStatus: %T", src)
	}
	return nil
}

type NullCaseStatus struct {
	CaseStatus CaseStatus `json:"case_status"`
	Valid      bool       `json:"valid"` // Valid is true if CaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CaseStatus), nil
}

type MarketType string

const (
	MarketTypeKR MarketType = "KR"
	MarketTypeUS MarketType = "US"
)

func (e *MarketType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarketType(s)
	case string:
		*e = MarketType(s)
	default:
		return fmt.Errorf("unsupported scan type for MarketType: %T", src)
	}
	return nil
}

type NullMarketType struct {
	MarketType MarketType `json:"market_type"`
	Valid      bool       `json:"valid"` // Valid is true if MarketType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarketType) Scan(value interface{}) error {
	if value == nil {
		ns.MarketType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarketType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarketType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarketType), nil
}

type MarketplaceItemType string

const (
	MarketplaceItemTypePIPELINE       MarketplaceItemType = "PIPELINE"
	MarketplaceItemTypeAGENTBLOCK     MarketplaceItemType = "AGENT_BLOCK"
	MarketplaceItemTypeSEARCHPRESET   MarketplaceItemType = "SEARCH_PRESET"
	MarketplaceItemTypeJUDGMENTSCRIPT MarketplaceItemType = "JUDGMENT_SCRIPT"
)

func (e *MarketplaceItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarketplaceItemType(s)
	case string:
		*e = MarketplaceItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for MarketplaceItemType: %T", src)
	}
	return nil
}

type NullMarketplaceItemType struct {
	MarketplaceItemType MarketplaceItemType `json:"marketplace_item_type"`
	Valid               bool                `json:"valid"` // Valid is true if MarketplaceItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarketplaceItemType) Scan(value interface{}) error {
	if value == nil {
		ns.MarketplaceItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarketplaceItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarketplaceItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarketplaceItemType), nil
}

type MarketplaceStatus string

const (
	MarketplaceStatusACTIVE  MarketplaceStatus = "ACTIVE"
	MarketplaceStatusHIDDEN  MarketplaceStatus = "HIDDEN"
	MarketplaceStatusREMOVED MarketplaceStatus = "REMOVED"
)

func (e *MarketplaceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarketplaceStatus(s)
	case string:
		*e = MarketplaceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MarketplaceStatus: %T", src)
	}
	return nil
}

type NullMarketplaceStatus struct {
	MarketplaceStatus MarketplaceStatus `json:"marketplace_status"`
	Valid             bool              `json:"valid"` // Valid is true if MarketplaceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarketplaceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MarketplaceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarketplaceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarketplaceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarketplaceStatus), nil
}

type TimelineEventType string

const (
	TimelineEventTypeNEWS           TimelineEventType = "NEWS"
	TimelineEventTypeDISCLOSURE     TimelineEventType = "DISCLOSURE"
	TimelineEventTypeSECTOR         TimelineEventType = "SECTOR"
	TimelineEventTypePRICEALERT     TimelineEventType = "PRICE_ALERT"
	TimelineEventTypeTRADE          TimelineEventType = "TRADE"
	TimelineEventTypePIPELINERESULT TimelineEventType = "PIPELINE_RESULT"
)

func (e *TimelineEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimelineEventType(s)
	case string:
		*e = TimelineEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for TimelineEventType: %T", src)
	}
	return nil
}

type NullTimelineEventType struct {
	TimelineEventType TimelineEventType `json:"timeline_event_type"`
	Valid             bool              `json:"valid"` // Valid is true if TimelineEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimelineEventType) Scan(value interface{}) error {
	if value == nil {
		ns.TimelineEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimelineEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimelineEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimelineEventType), nil
}

type TradeType string

const (
	TradeTypeBUY  TradeType = "BUY"
	TradeTypeSELL TradeType = "SELL"
)

func (e *TradeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradeType(s)
	case string:
		*e = TradeType(s)
	default:
		return fmt.Errorf("unsupported scan type for TradeType: %T", src)
	}
	return nil
}

type NullTradeType struct {
	TradeType TradeType `json:"trade_type"`
	Valid     bool      `json:"valid"` // Valid is true if TradeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradeType) Scan(value interface{}) error {
	if value == nil {
		ns.TradeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradeType), nil
}

type UsageAction string

const (
	UsageActionVIEW    UsageAction = "VIEW"
	UsageActionFORK    UsageAction = "FORK"
	UsageActionEXECUTE UsageAction = "EXECUTE"
	UsageActionLIKE    UsageAction = "LIKE"
)

func (e *UsageAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsageAction(s)
	case string:
		*e = UsageAction(s)
	default:
		return fmt.Errorf("unsupported scan type for UsageAction: %T", src)
	}
	return nil
}

type NullUsageAction struct {
	UsageAction UsageAction `json:"usage_action"`
	Valid       bool        `json:"valid"` // Valid is true if UsageAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsageAction) Scan(value interface{}) error {
	if value == nil {
		ns.UsageAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsageAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsageAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsageAction), nil
}

type AgentBlock struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Instruction  string             `json:"instruction"`
	SystemPrompt pgtype.Text        `json:"system_prompt"`
	AllowedTools []byte             `json:"allowed_tools"`
	OutputSchema []byte             `json:"output_schema"`
	IsPublic     bool               `json:"is_public"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Case struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	PipelineID    pgtype.UUID        `json:"pipeline_id"`
	Symbol        string             `json:"symbol"`
	Status        CaseStatus         `json:"status"`
	EventDate     pgtype.Date        `json:"event_date"`
	EventSnapshot []byte             `json:"event_snapshot"`
	SuccessScript string             `json:"success_script"`
	FailureScript string             `json:"failure_script"`
	ClosedAt      pgtype.Date        `json:"closed_at"`
	ClosedReason  pgtype.Text        `json:"closed_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FifoLot struct {
	ID           pgtype.UUID        `json:"id"`
	PositionID   pgtype.UUID        `json:"position_id"`
	TradeID      pgtype.UUID        `json:"trade_id"`
	BuyDate      pgtype.Timestamptz `json:"buy_date"`
	BuyPrice     pgtype.Numeric     `json:"buy_price"`
	OriginalQty  int32              `json:"original_qty"`
	RemainingQty int32              `json:"remaining_qty"`
	Fee          pgtype.Numeric     `json:"fee"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MarketplaceItem struct {
	ID                  pgtype.UUID         `json:"id"`
	UserID              pgtype.UUID         `json:"user_id"`
	Type                MarketplaceItemType `json:"type"`
	Title               string              `json:"title"`
	Description         string              `json:"description"`
	Tags                []string            `json:"tags"`
	PipelineID          pgtype.UUID         `json:"pipeline_id"`
	AgentBlockID        pgtype.UUID         `json:"agent_block_id"`
	SearchPresetID      pgtype.UUID         `json:"search_preset_id"`
	JudgmentScriptID    pgtype.UUID         `json:"judgment_script_id"`
	ForkedFromID        pgtype.UUID         `json:"forked_from_id"`
	ForkCount           int32               `json:"fork_count"`
	UsageCount          int32               `json:"usage_count"`
	ViewCount           int32               `json:"view_count"`
	LikeCount           int32               `json:"like_count"`
	Verified            bool                `json:"verified"`
	BacktestJobID       pgtype.UUID         `json:"backtest_job_id"`
	BacktestWinRate     pgtype.Numeric      `json:"backtest_win_rate"`
	BacktestAvgReturn   pgtype.Numeric      `json:"backtest_avg_return"`
	BacktestTotalEvents pgtype.Int4         `json:"backtest_total_events"`
	Status              MarketplaceStatus   `json:"status"`
	PublishedAt         pgtype.Timestamptz  `json:"published_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	SearchVector        interface{}         `json:"search_vector"`
}

type MarketplaceLike struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MarketplaceUsageLog struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	Action    UsageAction        `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Pipeline struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	AnalysisStages []byte             `json:"analysis_stages"`
	Monitors       []byte             `json:"monitors"`
	SuccessScript  string             `json:"success_script"`
	FailureScript  string             `json:"failure_script"`
	IsPublic       bool               `json:"is_public"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PortfolioPosition struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Symbol       string             `json:"symbol"`
	SymbolName   string             `json:"symbol_name"`
	Market       MarketType         `json:"market"`
	Quantity     int32              `json:"quantity"`
	AvgCostPrice pgtype.Numeric     `json:"avg_cost_price"`
	TotalCost    pgtype.Numeric     `json:"total_cost"`
	Sector       pgtype.Text        `json:"sector"`
	SectorName   pgtype.Text        `json:"sector_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PriceAlert struct {
	ID          pgtype.UUID        `json:"id"`
	CaseID      pgtype.UUID        `json:"case_id"`
	PipelineID  pgtype.UUID        `json:"pipeline_id"`
	Condition   string             `json:"condition"`
	Label       string             `json:"label"`
	Triggered   bool               `json:"triggered"`
	TriggeredAt pgtype.Date        `json:"triggered_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RealizedPnl struct {
	ID          pgtype.UUID        `json:"id"`
	PositionID  pgtype.UUID        `json:"position_id"`
	SellTradeID pgtype.UUID        `json:"sell_trade_id"`
	BuyLotID    pgtype.UUID        `json:"buy_lot_id"`
	Quantity    int32              `json:"quantity"`
	BuyPrice    pgtype.Numeric     `json:"buy_price"`
	SellPrice   pgtype.Numeric     `json:"sell_price"`
	GrossPnl    pgtype.Numeric     `json:"gross_pnl"`
	Fee         pgtype.Numeric     `json:"fee"`
	Tax         pgtype.Numeric     `json:"tax"`
	NetPnl      pgtype.Numeric     `json:"net_pnl"`
	RealizedAt  pgtype.Timestamptz `json:"realized_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TimelineEvent struct {
	ID         pgtype.UUID        `json:"id"`
	CaseID     pgtype.UUID        `json:"case_id"`
	Date       pgtype.Date        `json:"date"`
	Type       TimelineEventType  `json:"type"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	AiAnalysis pgtype.Text        `json:"ai_analysis"`
	Data       []byte             `json:"data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Trade struct {
	ID        pgtype.UUID        `json:"id"`
	CaseID    pgtype.UUID        `json:"case_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      TradeType          `json:"type"`
	Price     float64            `json:"price"`
	Quantity  int32              `json:"quantity"`
	Fee       float64            `json:"fee"`
	Date      pgtype.Date        `json:"date"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
