// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitoring.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableMonitorBlocksByCase = `-- name: DisableMonitorBlocksByCase :exec
UPDATE monitor_blocks SET enabled = false WHERE case_id = $1
`

// 라이프사이클: 케이스의 모든 모니터 블록 비활성화
func (q *Queries) DisableMonitorBlocksByCase(ctx context.Context, caseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableMonitorBlocksByCase, caseID)
	return err
}

const getCaseEventSnapshot = `-- name: GetCaseEventSnapshot :one
SELECT id, event_snapshot
FROM cases
WHERE id = $1
`

type GetCaseEventSnapshotRow struct {
	ID            pgtype.UUID `json:"id"`
	EventSnapshot []byte      `json:"event_snapshot"`
}

// 에이전트 핸들러: 케이스 이벤트 스냅샷 조회
func (q *Queries) GetCaseEventSnapshot(ctx context.Context, id pgtype.UUID) (GetCaseEventSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getCaseEventSnapshot, id)
	var i GetCaseEventSnapshotRow
	err := row.Scan(&i.ID, &i.EventSnapshot)
	return i, err
}

const listActiveMonitorBlocks = `-- name: ListActiveMonitorBlocks :many
SELECT mb.id AS monitor_block_id,
       c.id  AS case_id,
       c.pipeline_id,
       c.symbol,
       mb.cron,
       ab.instruction AS block_instruction,
       ab.allowed_tools
FROM monitor_blocks mb
JOIN cases c ON c.id = mb.case_id
JOIN agent_blocks ab ON ab.id = mb.block_id
WHERE mb.enabled = true AND c.status = 'LIVE'
`

type ListActiveMonitorBlocksRow struct {
	MonitorBlockID   pgtype.UUID `json:"monitor_block_id"`
	CaseID           pgtype.UUID `json:"case_id"`
	PipelineID       pgtype.UUID `json:"pipeline_id"`
	Symbol           string      `json:"symbol"`
	Cron             string      `json:"cron"`
	BlockInstruction string      `json:"block_instruction"`
	AllowedTools     []byte      `json:"allowed_tools"`
}

// 스케줄러 동기화: LIVE 케이스의 enabled MonitorBlock 조회
func (q *Queries) ListActiveMonitorBlocks(ctx context.Context) ([]ListActiveMonitorBlocksRow, error) {
	rows, err := q.db.Query(ctx, listActiveMonitorBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMonitorBlocksRow{}
	for rows.Next() {
		var i ListActiveMonitorBlocksRow
		if err := rows.Scan(
			&i.MonitorBlockID,
			&i.CaseID,
			&i.PipelineID,
			&i.Symbol,
			&i.Cron,
			&i.BlockInstruction,
			&i.AllowedTools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCases = `-- name: ListLiveCases :many
SELECT id, symbol, success_script, failure_script, event_snapshot
FROM cases
WHERE status = 'LIVE' AND dsl_polling_enabled = true
`

type ListLiveCasesRow struct {
	ID            pgtype.UUID `json:"id"`
	Symbol        string      `json:"symbol"`
	SuccessScript string      `json:"success_script"`
	FailureScript string      `json:"failure_script"`
	EventSnapshot []byte      `json:"event_snapshot"`
}

// DSL 폴러: LIVE 상태 + DSL 폴링 활성 케이스 목록
func (q *Queries) ListLiveCases(ctx context.Context) ([]ListLiveCasesRow, error) {
	rows, err := q.db.Query(ctx, listLiveCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveCasesRow{}
	for rows.Next() {
		var i ListLiveCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.SuccessScript,
			&i.FailureScript,
			&i.EventSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorBlocksByCase = `-- name: ListMonitorBlocksByCase :many
SELECT mb.id, mb.enabled, mb.cron, mb.last_executed_at, ab.instruction
FROM monitor_blocks mb
JOIN agent_blocks ab ON ab.id = mb.block_id
WHERE mb.case_id = $1
`

type ListMonitorBlocksByCaseRow struct {
	ID             pgtype.UUID        `json:"id"`
	Enabled        bool               `json:"enabled"`
	Cron           string             `json:"cron"`
	LastExecutedAt pgtype.Timestamptz `json:"last_executed_at"`
	Instruction    string             `json:"instruction"`
}

// 서비스: 케이스별 모니터 블록 목록 조회
func (q *Queries) ListMonitorBlocksByCase(ctx context.Context, caseID pgtype.UUID) ([]ListMonitorBlocksByCaseRow, error) {
	rows, err := q.db.Query(ctx, listMonitorBlocksByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitorBlocksByCaseRow{}
	for rows.Next() {
		var i ListMonitorBlocksByCaseRow
		if err := rows.Scan(
			&i.ID,
			&i.Enabled,
			&i.Cron,
			&i.LastExecutedAt,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntriggeredAlertsByCase = `-- name: ListUntriggeredAlertsByCase :many
SELECT id, condition, label
FROM price_alerts
WHERE case_id = $1 AND triggered = false
`

type ListUntriggeredAlertsByCaseRow struct {
	ID        pgtype.UUID `json:"id"`
	Condition string      `json:"condition"`
	Label     string      `json:"label"`
}

// DSL 폴러: 미트리거 가격 알림 조회
func (q *Queries) ListUntriggeredAlertsByCase(ctx context.Context, caseID pgtype.UUID) ([]ListUntriggeredAlertsByCaseRow, error) {
	rows, err := q.db.Query(ctx, listUntriggeredAlertsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUntriggeredAlertsByCaseRow{}
	for rows.Next() {
		var i ListUntriggeredAlertsByCaseRow
		if err := rows.Scan(&i.ID, &i.Condition, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaseDSLPollingEnabled = `-- name: UpdateCaseDSLPollingEnabled :exec
UPDATE cases SET dsl_polling_enabled = $2 WHERE id = $1
`

type UpdateCaseDSLPollingEnabledParams struct {
	ID                pgtype.UUID `json:"id"`
	DslPollingEnabled bool        `json:"dsl_polling_enabled"`
}

// 서비스: DSL 폴링 활성/비활성 토글
func (q *Queries) UpdateCaseDSLPollingEnabled(ctx context.Context, arg UpdateCaseDSLPollingEnabledParams) error {
	_, err := q.db.Exec(ctx, updateCaseDSLPollingEnabled, arg.ID, arg.DslPollingEnabled)
	return err
}

const updateMonitorBlockEnabled = `-- name: UpdateMonitorBlockEnabled :exec
UPDATE monitor_blocks SET enabled = $2 WHERE id = $1
`

type UpdateMonitorBlockEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled bool        `json:"enabled"`
}

// 서비스: 개별 모니터 블록 활성/비활성
func (q *Queries) UpdateMonitorBlockEnabled(ctx context.Context, arg UpdateMonitorBlockEnabledParams) error {
	_, err := q.db.Exec(ctx, updateMonitorBlockEnabled, arg.ID, arg.Enabled)
	return err
}

const updateMonitorBlockLastExecuted = `-- name: UpdateMonitorBlockLastExecuted :exec
UPDATE monitor_blocks SET last_executed_at = $2 WHERE id = $1
`

type UpdateMonitorBlockLastExecutedParams struct {
	ID             pgtype.UUID        `json:"id"`
	LastExecutedAt pgtype.Timestamptz `json:"last_executed_at"`
}

// 에이전트 핸들러: 마지막 실행 시간 업데이트
func (q *Queries) UpdateMonitorBlockLastExecuted(ctx context.Context, arg UpdateMonitorBlockLastExecutedParams) error {
	_, err := q.db.Exec(ctx, updateMonitorBlockLastExecuted, arg.ID, arg.LastExecutedAt)
	return err
}

const updateMonitorBlocksEnabledByCase = `-- name: UpdateMonitorBlocksEnabledByCase :exec
UPDATE monitor_blocks SET enabled = $2 WHERE case_id = $1
`

type UpdateMonitorBlocksEnabledByCaseParams struct {
	CaseID  pgtype.UUID `json:"case_id"`
	Enabled bool        `json:"enabled"`
}

// 서비스: 케이스 전체 모니터 블록 활성/비활성
func (q *Queries) UpdateMonitorBlocksEnabledByCase(ctx context.Context, arg UpdateMonitorBlocksEnabledByCaseParams) error {
	_, err := q.db.Exec(ctx, updateMonitorBlocksEnabledByCase, arg.CaseID, arg.Enabled)
	return err
}
