// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipelines.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPipelinesByUser = `-- name: CountPipelinesByUser :one
SELECT count(*) FROM pipelines WHERE user_id = $1
`

func (q *Queries) CountPipelinesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPipelinesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (user_id, name, description, success_script, failure_script, is_public)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, success_script, failure_script, is_public, created_at, updated_at
`

type CreatePipelineParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	SuccessScript pgtype.Text `json:"success_script"`
	FailureScript pgtype.Text `json:"failure_script"`
	IsPublic      bool        `json:"is_public"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.SuccessScript,
		arg.FailureScript,
		arg.IsPublic,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SuccessScript,
		&i.FailureScript,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipelineJob = `-- name: CreatePipelineJob :one
INSERT INTO pipeline_jobs (pipeline_id, symbol, status)
VALUES ($1, $2, 'PENDING')
RETURNING id, pipeline_id, symbol, status, result, error, started_at, completed_at, created_at
`

type CreatePipelineJobParams struct {
	PipelineID pgtype.UUID `json:"pipeline_id"`
	Symbol     string      `json:"symbol"`
}

func (q *Queries) CreatePipelineJob(ctx context.Context, arg CreatePipelineJobParams) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, createPipelineJob, arg.PipelineID, arg.Symbol)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Symbol,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStage = `-- name: CreateStage :one
INSERT INTO stages (pipeline_id, section, order_index)
VALUES ($1, $2, $3)
RETURNING id, pipeline_id, section, order_index, created_at
`

type CreateStageParams struct {
	PipelineID pgtype.UUID `json:"pipeline_id"`
	Section    string      `json:"section"`
	OrderIndex int32       `json:"order_index"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage, arg.PipelineID, arg.Section, arg.OrderIndex)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Section,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitorsByPipeline = `-- name: DeleteMonitorsByPipeline :exec
DELETE FROM monitor_blocks WHERE pipeline_id = $1
`

func (q *Queries) DeleteMonitorsByPipeline(ctx context.Context, pipelineID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitorsByPipeline, pipelineID)
	return err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines WHERE id = $1 AND user_id = $2
`

type DeletePipelineParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePipeline(ctx context.Context, arg DeletePipelineParams) error {
	_, err := q.db.Exec(ctx, deletePipeline, arg.ID, arg.UserID)
	return err
}

const deletePriceAlertsByPipeline = `-- name: DeletePriceAlertsByPipeline :exec
DELETE FROM price_alerts WHERE pipeline_id = $1
`

func (q *Queries) DeletePriceAlertsByPipeline(ctx context.Context, pipelineID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePriceAlertsByPipeline, pipelineID)
	return err
}

const deleteStagesByPipeline = `-- name: DeleteStagesByPipeline :exec
DELETE FROM stages WHERE pipeline_id = $1
`

func (q *Queries) DeleteStagesByPipeline(ctx context.Context, pipelineID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStagesByPipeline, pipelineID)
	return err
}

const getPipelineByID = `-- name: GetPipelineByID :one
SELECT id, user_id, name, description, success_script, failure_script, is_public, created_at, updated_at FROM pipelines WHERE id = $1 AND user_id = $2
`

type GetPipelineByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPipelineByID(ctx context.Context, arg GetPipelineByIDParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByID, arg.ID, arg.UserID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SuccessScript,
		&i.FailureScript,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineJob = `-- name: GetPipelineJob :one
SELECT id, pipeline_id, symbol, status, result, error, started_at, completed_at, created_at FROM pipeline_jobs WHERE id = $1
`

func (q *Queries) GetPipelineJob(ctx context.Context, id pgtype.UUID) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, getPipelineJob, id)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Symbol,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPipelinesByUser = `-- name: ListPipelinesByUser :many
SELECT id, user_id, name, description, success_script, failure_script, is_public, created_at, updated_at FROM pipelines WHERE user_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListPipelinesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListPipelinesByUser(ctx context.Context, arg ListPipelinesByUserParams) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.SuccessScript,
			&i.FailureScript,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesByPipeline = `-- name: ListStagesByPipeline :many
SELECT id, pipeline_id, section, order_index, created_at FROM stages WHERE pipeline_id = $1 ORDER BY order_index
`

func (q *Queries) ListStagesByPipeline(ctx context.Context, pipelineID pgtype.UUID) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStagesByPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Section,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipeline = `-- name: UpdatePipeline :one
UPDATE pipelines
SET name = $3, description = $4, success_script = $5, failure_script = $6, is_public = $7, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, success_script, failure_script, is_public, created_at, updated_at
`

type UpdatePipelineParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	SuccessScript pgtype.Text `json:"success_script"`
	FailureScript pgtype.Text `json:"failure_script"`
	IsPublic      bool        `json:"is_public"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, updatePipeline,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.SuccessScript,
		arg.FailureScript,
		arg.IsPublic,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SuccessScript,
		&i.FailureScript,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePipelineJobStatus = `-- name: UpdatePipelineJobStatus :one
UPDATE pipeline_jobs
SET status = $2, result = $3, error = $4, started_at = $5, completed_at = $6
WHERE id = $1
RETURNING id, pipeline_id, symbol, status, result, error, started_at, completed_at, created_at
`

type UpdatePipelineJobStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Result      []byte             `json:"result"`
	Error       pgtype.Text        `json:"error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdatePipelineJobStatus(ctx context.Context, arg UpdatePipelineJobStatusParams) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, updatePipelineJobStatus,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Symbol,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
