// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipelines.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPipelinesByUser = `-- name: CountPipelinesByUser :one
SELECT count(*) FROM pipelines WHERE user_id = $1
`

func (q *Queries) CountPipelinesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPipelinesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (user_id, name, description, analysis_stages, monitors, success_script, failure_script)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, name, description, analysis_stages, monitors, success_script, failure_script, is_public, created_at, updated_at
`

type CreatePipelineParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	AnalysisStages []byte      `json:"analysis_stages"`
	Monitors       []byte      `json:"monitors"`
	SuccessScript  string      `json:"success_script"`
	FailureScript  string      `json:"failure_script"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.AnalysisStages,
		arg.Monitors,
		arg.SuccessScript,
		arg.FailureScript,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.AnalysisStages,
		&i.Monitors,
		&i.SuccessScript,
		&i.FailureScript,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines WHERE id = $1 AND user_id = $2
`

type DeletePipelineParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePipeline(ctx context.Context, arg DeletePipelineParams) error {
	_, err := q.db.Exec(ctx, deletePipeline, arg.ID, arg.UserID)
	return err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, user_id, name, description, analysis_stages, monitors, success_script, failure_script, is_public, created_at, updated_at FROM pipelines WHERE id = $1 AND user_id = $2
`

type GetPipelineParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPipeline(ctx context.Context, arg GetPipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipeline, arg.ID, arg.UserID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.AnalysisStages,
		&i.Monitors,
		&i.SuccessScript,
		&i.FailureScript,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPipelinesByUser = `-- name: ListPipelinesByUser :many
SELECT id, user_id, name, description, analysis_stages, monitors, success_script, failure_script, is_public, created_at, updated_at FROM pipelines WHERE user_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListPipelinesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListPipelinesByUser(ctx context.Context, arg ListPipelinesByUserParams) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.AnalysisStages,
			&i.Monitors,
			&i.SuccessScript,
			&i.FailureScript,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipeline = `-- name: UpdatePipeline :one
UPDATE pipelines SET name = $2, description = $3, analysis_stages = $4, monitors = $5, success_script = $6, failure_script = $7
WHERE id = $1 RETURNING id, user_id, name, description, analysis_stages, monitors, success_script, failure_script, is_public, created_at, updated_at
`

type UpdatePipelineParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	AnalysisStages []byte      `json:"analysis_stages"`
	Monitors       []byte      `json:"monitors"`
	SuccessScript  string      `json:"success_script"`
	FailureScript  string      `json:"failure_script"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, updatePipeline,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AnalysisStages,
		arg.Monitors,
		arg.SuccessScript,
		arg.FailureScript,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.AnalysisStages,
		&i.Monitors,
		&i.SuccessScript,
		&i.FailureScript,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
