// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFifoLot = `-- name: CreateFifoLot :one
INSERT INTO fifo_lots (position_id, trade_id, buy_date, buy_price, original_qty, remaining_qty, fee)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, position_id, trade_id, buy_date, buy_price, original_qty, remaining_qty, fee, created_at
`

type CreateFifoLotParams struct {
	PositionID   pgtype.UUID        `json:"position_id"`
	TradeID      pgtype.UUID        `json:"trade_id"`
	BuyDate      pgtype.Timestamptz `json:"buy_date"`
	BuyPrice     pgtype.Numeric     `json:"buy_price"`
	OriginalQty  int32              `json:"original_qty"`
	RemainingQty int32              `json:"remaining_qty"`
	Fee          pgtype.Numeric     `json:"fee"`
}

func (q *Queries) CreateFifoLot(ctx context.Context, arg CreateFifoLotParams) (FifoLot, error) {
	row := q.db.QueryRow(ctx, createFifoLot,
		arg.PositionID,
		arg.TradeID,
		arg.BuyDate,
		arg.BuyPrice,
		arg.OriginalQty,
		arg.RemainingQty,
		arg.Fee,
	)
	var i FifoLot
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.TradeID,
		&i.BuyDate,
		&i.BuyPrice,
		&i.OriginalQty,
		&i.RemainingQty,
		&i.Fee,
		&i.CreatedAt,
	)
	return i, err
}

const createRealizedPnL = `-- name: CreateRealizedPnL :one
INSERT INTO realized_pnls (position_id, sell_trade_id, buy_lot_id, quantity, buy_price, sell_price, gross_pnl, fee, tax, net_pnl, realized_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, position_id, sell_trade_id, buy_lot_id, quantity, buy_price, sell_price, gross_pnl, fee, tax, net_pnl, realized_at, created_at
`

type CreateRealizedPnLParams struct {
	PositionID  pgtype.UUID        `json:"position_id"`
	SellTradeID pgtype.UUID        `json:"sell_trade_id"`
	BuyLotID    pgtype.UUID        `json:"buy_lot_id"`
	Quantity    int32              `json:"quantity"`
	BuyPrice    pgtype.Numeric     `json:"buy_price"`
	SellPrice   pgtype.Numeric     `json:"sell_price"`
	GrossPnl    pgtype.Numeric     `json:"gross_pnl"`
	Fee         pgtype.Numeric     `json:"fee"`
	Tax         pgtype.Numeric     `json:"tax"`
	NetPnl      pgtype.Numeric     `json:"net_pnl"`
	RealizedAt  pgtype.Timestamptz `json:"realized_at"`
}

func (q *Queries) CreateRealizedPnL(ctx context.Context, arg CreateRealizedPnLParams) (RealizedPnl, error) {
	row := q.db.QueryRow(ctx, createRealizedPnL,
		arg.PositionID,
		arg.SellTradeID,
		arg.BuyLotID,
		arg.Quantity,
		arg.BuyPrice,
		arg.SellPrice,
		arg.GrossPnl,
		arg.Fee,
		arg.Tax,
		arg.NetPnl,
		arg.RealizedAt,
	)
	var i RealizedPnl
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.SellTradeID,
		&i.BuyLotID,
		&i.Quantity,
		&i.BuyPrice,
		&i.SellPrice,
		&i.GrossPnl,
		&i.Fee,
		&i.Tax,
		&i.NetPnl,
		&i.RealizedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, user_id, symbol, symbol_name, market, quantity, avg_cost_price, total_cost, sector, sector_name, created_at, updated_at FROM portfolio_positions
WHERE id = $1
`

func (q *Queries) GetPositionByID(ctx context.Context, id pgtype.UUID) (PortfolioPosition, error) {
	row := q.db.QueryRow(ctx, getPositionByID, id)
	var i PortfolioPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.SymbolName,
		&i.Market,
		&i.Quantity,
		&i.AvgCostPrice,
		&i.TotalCost,
		&i.Sector,
		&i.SectorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionByUserSymbol = `-- name: GetPositionByUserSymbol :one
SELECT id, user_id, symbol, symbol_name, market, quantity, avg_cost_price, total_cost, sector, sector_name, created_at, updated_at FROM portfolio_positions
WHERE user_id = $1 AND symbol = $2
`

type GetPositionByUserSymbolParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Symbol string      `json:"symbol"`
}

func (q *Queries) GetPositionByUserSymbol(ctx context.Context, arg GetPositionByUserSymbolParams) (PortfolioPosition, error) {
	row := q.db.QueryRow(ctx, getPositionByUserSymbol, arg.UserID, arg.Symbol)
	var i PortfolioPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.SymbolName,
		&i.Market,
		&i.Quantity,
		&i.AvgCostPrice,
		&i.TotalCost,
		&i.Sector,
		&i.SectorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveLotsByPosition = `-- name: ListActiveLotsByPosition :many
SELECT id, position_id, trade_id, buy_date, buy_price, original_qty, remaining_qty, fee, created_at FROM fifo_lots
WHERE position_id = $1 AND remaining_qty > 0
ORDER BY buy_date ASC
`

func (q *Queries) ListActiveLotsByPosition(ctx context.Context, positionID pgtype.UUID) ([]FifoLot, error) {
	rows, err := q.db.Query(ctx, listActiveLotsByPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FifoLot{}
	for rows.Next() {
		var i FifoLot
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.TradeID,
			&i.BuyDate,
			&i.BuyPrice,
			&i.OriginalQty,
			&i.RemainingQty,
			&i.Fee,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPositionsByUser = `-- name: ListAllPositionsByUser :many
SELECT id, user_id, symbol, symbol_name, market, quantity, avg_cost_price, total_cost, sector, sector_name, created_at, updated_at FROM portfolio_positions
WHERE user_id = $1
ORDER BY symbol
`

func (q *Queries) ListAllPositionsByUser(ctx context.Context, userID pgtype.UUID) ([]PortfolioPosition, error) {
	rows, err := q.db.Query(ctx, listAllPositionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioPosition{}
	for rows.Next() {
		var i PortfolioPosition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.SymbolName,
			&i.Market,
			&i.Quantity,
			&i.AvgCostPrice,
			&i.TotalCost,
			&i.Sector,
			&i.SectorName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByUser = `-- name: ListPositionsByUser :many
SELECT id, user_id, symbol, symbol_name, market, quantity, avg_cost_price, total_cost, sector, sector_name, created_at, updated_at FROM portfolio_positions
WHERE user_id = $1 AND quantity > 0
ORDER BY symbol
`

func (q *Queries) ListPositionsByUser(ctx context.Context, userID pgtype.UUID) ([]PortfolioPosition, error) {
	rows, err := q.db.Query(ctx, listPositionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioPosition{}
	for rows.Next() {
		var i PortfolioPosition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.SymbolName,
			&i.Market,
			&i.Quantity,
			&i.AvgCostPrice,
			&i.TotalCost,
			&i.Sector,
			&i.SectorName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRealizedPnLByPosition = `-- name: ListRealizedPnLByPosition :many
SELECT id, position_id, sell_trade_id, buy_lot_id, quantity, buy_price, sell_price, gross_pnl, fee, tax, net_pnl, realized_at, created_at FROM realized_pnls
WHERE position_id = $1
ORDER BY realized_at DESC
`

func (q *Queries) ListRealizedPnLByPosition(ctx context.Context, positionID pgtype.UUID) ([]RealizedPnl, error) {
	rows, err := q.db.Query(ctx, listRealizedPnLByPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealizedPnl{}
	for rows.Next() {
		var i RealizedPnl
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.SellTradeID,
			&i.BuyLotID,
			&i.Quantity,
			&i.BuyPrice,
			&i.SellPrice,
			&i.GrossPnl,
			&i.Fee,
			&i.Tax,
			&i.NetPnl,
			&i.RealizedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRealizedPnLByUserPeriod = `-- name: ListRealizedPnLByUserPeriod :many
SELECT rp.id, rp.position_id, rp.sell_trade_id, rp.buy_lot_id, rp.quantity, rp.buy_price, rp.sell_price, rp.gross_pnl, rp.fee, rp.tax, rp.net_pnl, rp.realized_at, rp.created_at
FROM realized_pnls rp
JOIN portfolio_positions pp ON rp.position_id = pp.id
WHERE pp.user_id = $1
  AND rp.realized_at >= $2
  AND rp.realized_at <= $3
ORDER BY rp.realized_at ASC
`

type ListRealizedPnLByUserPeriodParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	RealizedAt   pgtype.Timestamptz `json:"realized_at"`
	RealizedAt_2 pgtype.Timestamptz `json:"realized_at_2"`
}

func (q *Queries) ListRealizedPnLByUserPeriod(ctx context.Context, arg ListRealizedPnLByUserPeriodParams) ([]RealizedPnl, error) {
	rows, err := q.db.Query(ctx, listRealizedPnLByUserPeriod, arg.UserID, arg.RealizedAt, arg.RealizedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealizedPnl{}
	for rows.Next() {
		var i RealizedPnl
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.SellTradeID,
			&i.BuyLotID,
			&i.Quantity,
			&i.BuyPrice,
			&i.SellPrice,
			&i.GrossPnl,
			&i.Fee,
			&i.Tax,
			&i.NetPnl,
			&i.RealizedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRealizedPnLByUser = `-- name: SumRealizedPnLByUser :one
SELECT COALESCE(SUM(rp.net_pnl), 0)::NUMERIC(12,2) AS total_net_pnl
FROM realized_pnls rp
JOIN portfolio_positions pp ON rp.position_id = pp.id
WHERE pp.user_id = $1
`

func (q *Queries) SumRealizedPnLByUser(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumRealizedPnLByUser, userID)
	var total_net_pnl pgtype.Numeric
	err := row.Scan(&total_net_pnl)
	return total_net_pnl, err
}

const sumRealizedPnLByUserAndMarket = `-- name: SumRealizedPnLByUserAndMarket :one
SELECT COALESCE(SUM(rp.net_pnl), 0)::NUMERIC(12,2) AS total_net_pnl,
       COALESCE(SUM(rp.gross_pnl), 0)::NUMERIC(12,2) AS total_gross_pnl,
       COALESCE(SUM(rp.tax), 0)::NUMERIC(12,2) AS total_tax,
       COALESCE(SUM(rp.sell_price * rp.quantity), 0)::NUMERIC(12,2) AS total_sell_amount
FROM realized_pnls rp
JOIN portfolio_positions pp ON rp.position_id = pp.id
WHERE pp.user_id = $1 AND pp.market = $2
`

type SumRealizedPnLByUserAndMarketParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Market MarketType  `json:"market"`
}

type SumRealizedPnLByUserAndMarketRow struct {
	TotalNetPnl     pgtype.Numeric `json:"total_net_pnl"`
	TotalGrossPnl   pgtype.Numeric `json:"total_gross_pnl"`
	TotalTax        pgtype.Numeric `json:"total_tax"`
	TotalSellAmount pgtype.Numeric `json:"total_sell_amount"`
}

func (q *Queries) SumRealizedPnLByUserAndMarket(ctx context.Context, arg SumRealizedPnLByUserAndMarketParams) (SumRealizedPnLByUserAndMarketRow, error) {
	row := q.db.QueryRow(ctx, sumRealizedPnLByUserAndMarket, arg.UserID, arg.Market)
	var i SumRealizedPnLByUserAndMarketRow
	err := row.Scan(
		&i.TotalNetPnl,
		&i.TotalGrossPnl,
		&i.TotalTax,
		&i.TotalSellAmount,
	)
	return i, err
}

const updateLotRemainingQty = `-- name: UpdateLotRemainingQty :exec
UPDATE fifo_lots
SET remaining_qty = $2
WHERE id = $1
`

type UpdateLotRemainingQtyParams struct {
	ID           pgtype.UUID `json:"id"`
	RemainingQty int32       `json:"remaining_qty"`
}

func (q *Queries) UpdateLotRemainingQty(ctx context.Context, arg UpdateLotRemainingQtyParams) error {
	_, err := q.db.Exec(ctx, updateLotRemainingQty, arg.ID, arg.RemainingQty)
	return err
}

const updatePositionAggregates = `-- name: UpdatePositionAggregates :exec
UPDATE portfolio_positions
SET quantity = $2, avg_cost_price = $3, total_cost = $4, updated_at = now()
WHERE id = $1
`

type UpdatePositionAggregatesParams struct {
	ID           pgtype.UUID    `json:"id"`
	Quantity     int32          `json:"quantity"`
	AvgCostPrice pgtype.Numeric `json:"avg_cost_price"`
	TotalCost    pgtype.Numeric `json:"total_cost"`
}

func (q *Queries) UpdatePositionAggregates(ctx context.Context, arg UpdatePositionAggregatesParams) error {
	_, err := q.db.Exec(ctx, updatePositionAggregates,
		arg.ID,
		arg.Quantity,
		arg.AvgCostPrice,
		arg.TotalCost,
	)
	return err
}

const upsertPortfolioPosition = `-- name: UpsertPortfolioPosition :one
INSERT INTO portfolio_positions (user_id, symbol, symbol_name, market, quantity, avg_cost_price, total_cost, sector, sector_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, symbol) DO UPDATE SET
  quantity = portfolio_positions.quantity,
  avg_cost_price = portfolio_positions.avg_cost_price,
  total_cost = portfolio_positions.total_cost,
  updated_at = now()
RETURNING id, user_id, symbol, symbol_name, market, quantity, avg_cost_price, total_cost, sector, sector_name, created_at, updated_at
`

type UpsertPortfolioPositionParams struct {
	UserID       pgtype.UUID    `json:"user_id"`
	Symbol       string         `json:"symbol"`
	SymbolName   string         `json:"symbol_name"`
	Market       MarketType     `json:"market"`
	Quantity     int32          `json:"quantity"`
	AvgCostPrice pgtype.Numeric `json:"avg_cost_price"`
	TotalCost    pgtype.Numeric `json:"total_cost"`
	Sector       pgtype.Text    `json:"sector"`
	SectorName   pgtype.Text    `json:"sector_name"`
}

func (q *Queries) UpsertPortfolioPosition(ctx context.Context, arg UpsertPortfolioPositionParams) (PortfolioPosition, error) {
	row := q.db.QueryRow(ctx, upsertPortfolioPosition,
		arg.UserID,
		arg.Symbol,
		arg.SymbolName,
		arg.Market,
		arg.Quantity,
		arg.AvgCostPrice,
		arg.TotalCost,
		arg.Sector,
		arg.SectorName,
	)
	var i PortfolioPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.SymbolName,
		&i.Market,
		&i.Quantity,
		&i.AvgCostPrice,
		&i.TotalCost,
		&i.Sector,
		&i.SectorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
