// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPresets = `-- name: CountPresets :one
SELECT COUNT(*) FROM search_presets
WHERE user_id = $1 OR is_public = true
`

func (q *Queries) CountPresets(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPresets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPreset = `-- name: CreatePreset :one
INSERT INTO search_presets (user_id, name, dsl, nl_query, is_public)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, dsl, nl_query, is_public, created_at, updated_at
`

type CreatePresetParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Dsl      string      `json:"dsl"`
	NlQuery  pgtype.Text `json:"nl_query"`
	IsPublic bool        `json:"is_public"`
}

func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (SearchPreset, error) {
	row := q.db.QueryRow(ctx, createPreset,
		arg.UserID,
		arg.Name,
		arg.Dsl,
		arg.NlQuery,
		arg.IsPublic,
	)
	var i SearchPreset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Dsl,
		&i.NlQuery,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePreset = `-- name: DeletePreset :exec
DELETE FROM search_presets WHERE id = $1 AND user_id = $2
`

type DeletePresetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePreset(ctx context.Context, arg DeletePresetParams) error {
	_, err := q.db.Exec(ctx, deletePreset, arg.ID, arg.UserID)
	return err
}

const getPreset = `-- name: GetPreset :one
SELECT id, user_id, name, dsl, nl_query, is_public, created_at, updated_at FROM search_presets WHERE id = $1
`

func (q *Queries) GetPreset(ctx context.Context, id pgtype.UUID) (SearchPreset, error) {
	row := q.db.QueryRow(ctx, getPreset, id)
	var i SearchPreset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Dsl,
		&i.NlQuery,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresets = `-- name: ListPresets :many
SELECT id, user_id, name, dsl, nl_query, is_public, created_at, updated_at FROM search_presets
WHERE user_id = $1 OR is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPresetsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListPresets(ctx context.Context, arg ListPresetsParams) ([]SearchPreset, error) {
	rows, err := q.db.Query(ctx, listPresets, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPreset{}
	for rows.Next() {
		var i SearchPreset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Dsl,
			&i.NlQuery,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
