// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPriceAlert = `-- name: CreatePriceAlert :one
INSERT INTO price_alerts (case_id, pipeline_id, condition, label) VALUES ($1, $2, $3, $4) RETURNING id, case_id, pipeline_id, condition, label, triggered, triggered_at, created_at
`

type CreatePriceAlertParams struct {
	CaseID     pgtype.UUID `json:"case_id"`
	PipelineID pgtype.UUID `json:"pipeline_id"`
	Condition  string      `json:"condition"`
	Label      string      `json:"label"`
}

func (q *Queries) CreatePriceAlert(ctx context.Context, arg CreatePriceAlertParams) (PriceAlert, error) {
	row := q.db.QueryRow(ctx, createPriceAlert,
		arg.CaseID,
		arg.PipelineID,
		arg.Condition,
		arg.Label,
	)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.PipelineID,
		&i.Condition,
		&i.Label,
		&i.Triggered,
		&i.TriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePriceAlert = `-- name: DeletePriceAlert :exec
DELETE FROM price_alerts WHERE id = $1 AND case_id = $2
`

type DeletePriceAlertParams struct {
	ID     pgtype.UUID `json:"id"`
	CaseID pgtype.UUID `json:"case_id"`
}

func (q *Queries) DeletePriceAlert(ctx context.Context, arg DeletePriceAlertParams) error {
	_, err := q.db.Exec(ctx, deletePriceAlert, arg.ID, arg.CaseID)
	return err
}

const listPendingAlertsByCase = `-- name: ListPendingAlertsByCase :many
SELECT id, case_id, pipeline_id, condition, label, triggered, triggered_at, created_at FROM price_alerts WHERE case_id = $1 AND triggered = false ORDER BY created_at DESC
`

func (q *Queries) ListPendingAlertsByCase(ctx context.Context, caseID pgtype.UUID) ([]PriceAlert, error) {
	rows, err := q.db.Query(ctx, listPendingAlertsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.PipelineID,
			&i.Condition,
			&i.Label,
			&i.Triggered,
			&i.TriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAlertsByCase = `-- name: ListPriceAlertsByCase :many
SELECT id, case_id, pipeline_id, condition, label, triggered, triggered_at, created_at FROM price_alerts WHERE case_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPriceAlertsByCase(ctx context.Context, caseID pgtype.UUID) ([]PriceAlert, error) {
	rows, err := q.db.Query(ctx, listPriceAlertsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.PipelineID,
			&i.Condition,
			&i.Label,
			&i.Triggered,
			&i.TriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggeredAlertsByCase = `-- name: ListTriggeredAlertsByCase :many
SELECT id, case_id, pipeline_id, condition, label, triggered, triggered_at, created_at FROM price_alerts WHERE case_id = $1 AND triggered = true ORDER BY triggered_at DESC
`

func (q *Queries) ListTriggeredAlertsByCase(ctx context.Context, caseID pgtype.UUID) ([]PriceAlert, error) {
	rows, err := q.db.Query(ctx, listTriggeredAlertsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.PipelineID,
			&i.Condition,
			&i.Label,
			&i.Triggered,
			&i.TriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const triggerPriceAlert = `-- name: TriggerPriceAlert :one
UPDATE price_alerts SET triggered = true, triggered_at = $2 WHERE id = $1 RETURNING id, case_id, pipeline_id, condition, label, triggered, triggered_at, created_at
`

type TriggerPriceAlertParams struct {
	ID          pgtype.UUID `json:"id"`
	TriggeredAt pgtype.Date `json:"triggered_at"`
}

func (q *Queries) TriggerPriceAlert(ctx context.Context, arg TriggerPriceAlertParams) (PriceAlert, error) {
	row := q.db.QueryRow(ctx, triggerPriceAlert, arg.ID, arg.TriggeredAt)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.PipelineID,
		&i.Condition,
		&i.Label,
		&i.Triggered,
		&i.TriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}
