// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeline_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimelineEvent = `-- name: CreateTimelineEvent :one
INSERT INTO timeline_events (case_id, date, type, title, content, ai_analysis, data)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, case_id, date, type, title, content, ai_analysis, data, created_at
`

type CreateTimelineEventParams struct {
	CaseID     pgtype.UUID       `json:"case_id"`
	Date       pgtype.Date       `json:"date"`
	Type       TimelineEventType `json:"type"`
	Title      string            `json:"title"`
	Content    string            `json:"content"`
	AiAnalysis pgtype.Text       `json:"ai_analysis"`
	Data       []byte            `json:"data"`
}

func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (TimelineEvent, error) {
	row := q.db.QueryRow(ctx, createTimelineEvent,
		arg.CaseID,
		arg.Date,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.AiAnalysis,
		arg.Data,
	)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Date,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.AiAnalysis,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listTimelineEventsByCase = `-- name: ListTimelineEventsByCase :many
SELECT id, case_id, date, type, title, content, ai_analysis, data, created_at FROM timeline_events WHERE case_id = $1 ORDER BY date DESC
`

func (q *Queries) ListTimelineEventsByCase(ctx context.Context, caseID pgtype.UUID) ([]TimelineEvent, error) {
	rows, err := q.db.Query(ctx, listTimelineEventsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEvent{}
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Date,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.AiAnalysis,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
