// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (case_id, user_id, type, price, quantity, fee, date, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, case_id, user_id, type, price, quantity, fee, date, note, created_at
`

type CreateTradeParams struct {
	CaseID   pgtype.UUID `json:"case_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Type     TradeType   `json:"type"`
	Price    float64     `json:"price"`
	Quantity int32       `json:"quantity"`
	Fee      float64     `json:"fee"`
	Date     pgtype.Date `json:"date"`
	Note     pgtype.Text `json:"note"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.CaseID,
		arg.UserID,
		arg.Type,
		arg.Price,
		arg.Quantity,
		arg.Fee,
		arg.Date,
		arg.Note,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.UserID,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.Fee,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listTradesByCase = `-- name: ListTradesByCase :many
SELECT id, case_id, user_id, type, price, quantity, fee, date, note, created_at FROM trades WHERE case_id = $1 ORDER BY date DESC
`

func (q *Queries) ListTradesByCase(ctx context.Context, caseID pgtype.UUID) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTradesByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.UserID,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.Fee,
			&i.Date,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
