// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package sqlc

import (
	"context"
)

const addToWatchlist = `-- name: AddToWatchlist :one
INSERT INTO watchlist (user_id, symbol, name)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, symbol) DO UPDATE SET name = EXCLUDED.name
RETURNING id, user_id, symbol, name, created_at
`

type AddToWatchlistParams struct {
	UserID int64  `json:"user_id"`
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
}

func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, addToWatchlist, arg.UserID, arg.Symbol, arg.Name)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getWatchlistByUser = `-- name: GetWatchlistByUser :many
SELECT id, user_id, symbol, name, created_at
FROM watchlist
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWatchlistByUser(ctx context.Context, userID int64) ([]Watchlist, error) {
	rows, err := q.db.Query(ctx, getWatchlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Watchlist{}
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isInWatchlist = `-- name: IsInWatchlist :one
SELECT EXISTS(
    SELECT 1 FROM watchlist WHERE user_id = $1 AND symbol = $2
) AS is_in_watchlist
`

type IsInWatchlistParams struct {
	UserID int64  `json:"user_id"`
	Symbol string `json:"symbol"`
}

func (q *Queries) IsInWatchlist(ctx context.Context, arg IsInWatchlistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInWatchlist, arg.UserID, arg.Symbol)
	var is_in_watchlist bool
	err := row.Scan(&is_in_watchlist)
	return is_in_watchlist, err
}

const removeFromWatchlist = `-- name: RemoveFromWatchlist :exec
DELETE FROM watchlist
WHERE user_id = $1 AND symbol = $2
`

type RemoveFromWatchlistParams struct {
	UserID int64  `json:"user_id"`
	Symbol string `json:"symbol"`
}

func (q *Queries) RemoveFromWatchlist(ctx context.Context, arg RemoveFromWatchlistParams) error {
	_, err := q.db.Exec(ctx, removeFromWatchlist, arg.UserID, arg.Symbol)
	return err
}
